spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buddy_db
    username: gunmi_notebook
    password: geonhee0706m!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
